In [51]:
import pandas as pd

In [52]:
df = pd.read_csv('student_performance_prediction_dataset-2.csv')

In [53]:
df

,student_id,age,gender,study_hours,attendance,sleep_hours,previous_grade,assignments_completed,practice_tests_taken,group_study_hours,...,social_media_hours,family_income,parent_education,internet_access,device_type,school_type,extracurriculars,final_grade,grade_category,pass_fail
0,1,21,Male,1.645404,79.154521,8.230886,96.053840,7.719620,1.871170,1.447894,...,4.018412,Medium,Master,Yes,Mobile,Private,Coding Club,59.248749,D,Pass
1,2,18,Male,4.462126,72.526685,6.139219,53.024821,6.754758,5.630071,1.891288,...,3.268642,Medium,Master,Yes,Laptop,Public,NaN,58.595595,D,Pass
2,3,19,Female,6.220212,98.531716,6.946313,78.775422,10.000000,7.862877,1.774356,...,2.327293,Low,High School,Yes,Tablet,Private,Music,85.855289,A,Pass
3,4,21,Female,1.826644,97.731245,8.297048,76.122618,7.440486,2.316252,1.204271,...,1.163367,Medium,Bachelor,Yes,Laptop,Public,Debate,42.117503,F,Fail
4,5,17,Male,3.789322,78.589107,6.777171,81.305681,9.962609,5.335697,1.399230,...,0.411183,High,High School,Yes,Laptop,Private,Debate,62.870474,C,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,299996,20,Female,4.997969,74.093222,7.440359,52.347483,7.919553,6.528064,1.362207,...,4.708792,Medium,PhD,Yes,Mobile,Private,Arts,48.932617,F,Fail
299996,299997,17,Female,4.046644,90.982332,8.604581,83.542563,7.634545,4.677627,1.657900,...,2.797866,High,High School,Yes,Mobile,Public,Music,54.907427,D,Pass
299997,299998,16,Male,3.270361,62.681191,7.630534,72.803779,8.405001,2.453354,0.505174,...,3.264763,Medium,High School,Yes,Laptop,Public,Sports,30.199483,F,Fail
299998,299999,17,Female,1.907116,95.109287,6.341972,63.691808,9.025269,7.843200,0.000000,...,3.611083,Medium,Bachelor,Yes,NaN,Public,Music,65.075466,C,Pass
299999,300000,20,Male,0.498701,95.549121,4.670566,46.527411,5.306086,2.419068,3.301766,...,2.240141,Medium,Master,No,Tablet,Private,Sports,31.733528,F,Fail

In [54]:
df.head()

,student_id,age,gender,study_hours,attendance,sleep_hours,previous_grade,assignments_completed,practice_tests_taken,group_study_hours,...,social_media_hours,family_income,parent_education,internet_access,device_type,school_type,extracurriculars,final_grade,grade_category,pass_fail
0,1,21,Male,1.645404,79.154521,8.230886,96.053840,7.719620,1.871170,1.447894,...,4.018412,Medium,Master,Yes,Mobile,Private,Coding Club,59.248749,D,Pass
1,2,18,Male,4.462126,72.526685,6.139219,53.024821,6.754758,5.630071,1.891288,...,3.268642,Medium,Master,Yes,Laptop,Public,NaN,58.595595,D,Pass
2,3,19,Female,6.220212,98.531716,6.946313,78.775422,10.000000,7.862877,1.774356,...,2.327293,Low,High School,Yes,Tablet,Private,Music,85.855289,A,Pass
3,4,21,Female,1.826644,97.731245,8.297048,76.122618,7.440486,2.316252,1.204271,...,1.163367,Medium,Bachelor,Yes,Laptop,Public,Debate,42.117503,F,Fail
4,5,17,Male,3.789322,78.589107,6.777171,81.305681,9.962609,5.335697,1.399230,...,0.411183,High,High School,Yes,Laptop,Private,Debate,62.870474,C,Pass

In [55]:
df.tail()

,student_id,age,gender,study_hours,attendance,sleep_hours,previous_grade,assignments_completed,practice_tests_taken,group_study_hours,...,social_media_hours,family_income,parent_education,internet_access,device_type,school_type,extracurriculars,final_grade,grade_category,pass_fail
299995,299996,20,Female,4.997969,74.093222,7.440359,52.347483,7.919553,6.528064,1.362207,...,4.708792,Medium,PhD,Yes,Mobile,Private,Arts,48.932617,F,Fail
299996,299997,17,Female,4.046644,90.982332,8.604581,83.542563,7.634545,4.677627,1.657900,...,2.797866,High,High School,Yes,Mobile,Public,Music,54.907427,D,Pass
299997,299998,16,Male,3.270361,62.681191,7.630534,72.803779,8.405001,2.453354,0.505174,...,3.264763,Medium,High School,Yes,Laptop,Public,Sports,30.199483,F,Fail
299998,299999,17,Female,1.907116,95.109287,6.341972,63.691808,9.025269,7.843200,0.000000,...,3.611083,Medium,Bachelor,Yes,NaN,Public,Music,65.075466,C,Pass
299999,300000,20,Male,0.498701,95.549121,4.670566,46.527411,5.306086,2.419068,3.301766,...,2.240141,Medium,Master,No,Tablet,Private,Sports,31.733528,F,Fail

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 25 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   student_id             300000 non-null  int64
 1   age                    300000 non-null  int64
 2   gender                 300000 non-null  object
 3   study_hours            300000 non-null  float64
 4   attendance             300000 non-null  float64
 5   sleep_hours            300000 non-null  float64
 6   previous_grade         300000 non-null  float64
 7   assignments_completed  300000 non-null  float64
 8   practice_tests_taken   300000 non-null  float64
 9   group_study_hours      300000 non-null  float64
 10  notes_quality_score    300000 non-null  float64
 11  time_management_score  300000 non-null  float64
 12  motivation_level       300000 non-null  float64
 13  mental_health_score    300000 non-null  float64
 14  screen_time            300000 non-null  float64
 15  social_media_hours     300000 non-null  float64
 16  family_income          300000 non-null  object
 17  parent_education       300000 non-null  object
 18  internet_access        300000 non-null  object
 19  device_type            284895 non-null  object
 20  school_type            300000 non-null  object
 21  extracurriculars       250019 non-null  object
 22  final_grade            300000 non-null  float64
 23  grade_category         299996 non-null  object
 24  pass_fail              300000 non-null  object
dtypes: float64(14), int64(2), object(9)
memory usage: 57.2+ MB

In [57]:
df.describe()

,student_id,age,study_hours,attendance,sleep_hours,previous_grade,assignments_completed,practice_tests_taken,group_study_hours,notes_quality_score,time_management_score,motivation_level,mental_health_score,screen_time,social_media_hours,final_grade
count,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000
mean,150000.500000,17.999070,4.503062,84.699395,6.991431,69.840184,7.836044,4.017508,1.529057,6.946017,6.464472,6.945851,6.984210,4.018094,2.530258,53.089206
std,86602.684716,1.999235,1.978513,9.419450,1.463070,14.683157,1.732474,1.956444,0.941525,1.885193,1.925801,1.886246,1.471193,1.958596,1.435742,12.225161
min,1.000000,15.000000,0.000000,40.000000,3.000000,20.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,75000.750000,16.000000,3.143566,78.241008,5.992666,59.870863,6.654817,2.655243,0.826462,5.653740,5.138654,5.655885,5.982593,2.650836,1.491633,44.867737
50%,150000.500000,18.000000,4.498272,84.990371,6.999011,69.955736,8.000829,4.001981,1.499206,7.011212,6.493222,7.005390,6.992543,3.997134,2.498493,53.167495
75%,225000.250000,20.000000,5.843646,91.732244,8.013284,80.102857,9.357154,5.349494,2.172680,8.356150,7.845919,8.356416,8.010331,5.350158,3.513496,61.379373
max,300000.000000,21.000000,12.000000,100.000000,10.000000,100.000000,10.000000,10.000000,5.840593,10.000000,10.000000,10.000000,10.000000,12.000000,8.000000,100.000000

In [58]:
df.isnull().sum()

student_id                   0
age                          0
gender                       0
study_hours                  0
attendance                   0
sleep_hours                  0
previous_grade               0
assignments_completed        0
practice_tests_taken         0
group_study_hours            0
notes_quality_score          0
time_management_score        0
motivation_level             0
mental_health_score          0
screen_time                  0
social_media_hours           0
family_income                0
parent_education             0
internet_access              0
device_type              15105
school_type                  0
extracurriculars         49981
final_grade                  0
grade_category               4
pass_fail                    0
dtype: int64

In [59]:
df.duplicated().sum()

np.int64(0)

In [60]:
df.dtypes

student_id                 int64
age                        int64
gender                    object
study_hours              float64
attendance               float64
sleep_hours              float64
previous_grade           float64
assignments_completed    float64
practice_tests_taken     float64
group_study_hours        float64
notes_quality_score      float64
time_management_score    float64
motivation_level         float64
mental_health_score      float64
screen_time              float64
social_media_hours       float64
family_income             object
parent_education          object
internet_access           object
device_type               object
school_type               object
extracurriculars          object
final_grade              float64
grade_category            object
pass_fail                 object
dtype: object

In [61]:
y = df['final_grade']
X = df.drop(columns=['final_grade', 'pass_fail', 'grade_category', 'student_id'])
print("\nX shape:", X.shape)
print("y shape:", y.shape)

X shape: (300000, 21)
y shape: (300000,)

In [62]:
income_map = {'Low': 0, 'Medium': 1, 'High': 2}
X['family_income'] = X['family_income'].map(income_map)

edu_map = {'High School': 0, 'Bachelor': 1, 'Master': 2, 'PhD': 3}
X['parent_education'] = X['parent_education'].map(edu_map)

# Binary columns -> 0/1 mapping
X['internet_access'] = X['internet_access'].map({'No': 0, 'Yes': 1})
X['school_type'] = X['school_type'].map({'Public': 0, 'Private': 1})

# Nominal columns (no order) -> One-Hot Encoding
X = pd.get_dummies(X, columns=['gender', 'device_type', 'extracurriculars'], drop_first=True)

print("\nX shape after encoding:", X.shape)
print(X.head())

X shape after encoding: (300000, 26)
   age  study_hours  attendance  sleep_hours  previous_grade  \
0   21     1.645404   79.154521     8.230886       96.053840
1   18     4.462126   72.526685     6.139219       53.024821
2   19     6.220212   98.531716     6.946313       78.775422
3   21     1.826644   97.731245     8.297048       76.122618
4   17     3.789322   78.589107     6.777171       81.305681

   assignments_completed  practice_tests_taken  group_study_hours  \
0               7.719620              1.871170           1.447894
1               6.754758              5.630071           1.891288
2              10.000000              7.862877           1.774356
3               7.440486              2.316252           1.204271
4               9.962609              5.335697           1.399230

   notes_quality_score  time_management_score  ...  internet_access  \
0             6.811654               7.316867  ...                1
1            10.000000              10.000000  ...                1
2             6.484908               3.618888  ...                1
3             6.057978               5.366866  ...                1
4             9.013332               5.613393  ...                1

   school_type  gender_Male  gender_Other  device_type_Mobile  \
0            1         True         False                True
1            0         True         False               False
2            1        False         False               False
3            0        False         False               False
4            1         True         False               False

   device_type_Tablet  extracurriculars_Coding Club  extracurriculars_Debate  \
0               False                          True                    False
1               False                         False                    False
2                True                         False                    False
3               False                         False                     True
4               False                         False                     True

   extracurriculars_Music  extracurriculars_Sports
0                   False                    False
1                   False                    False
2                    True                    False
3                   False                    False
4                   False                    False

[5 rows x 26 columns]

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("\nX_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (210000, 26)
X_test shape: (90000, 26)

In [65]:
from sklearn.preprocessing import StandardScaler

In [66]:
numeric_cols = [
    'age', 'study_hours', 'attendance', 'sleep_hours', 'previous_grade',
    'assignments_completed', 'practice_tests_taken', 'group_study_hours',
    'notes_quality_score', 'time_management_score', 'motivation_level',
    'mental_health_score', 'screen_time', 'social_media_hours',
    'family_income', 'parent_education'
]

scaler =    StandardScaler()

# Fit sirf training data par, test data par sirf transform (data leakage avoid karne ke liye)
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

print("\n--- Scaled Training Data (Sample) ---")
print(X_train[numeric_cols].head())

print("\nPreprocessing Complete!")
print("Final X_train shape:", X_train.shape)
print("Final X_test shape:", X_test.shape)

--- Scaled Training Data (Sample) ---
             age  study_hours  attendance  sleep_hours  previous_grade  \
186295 -0.998583    -0.827666    1.007984    -0.554355       -1.309926
127847 -1.498623    -2.270800   -0.485789     0.659635       -0.592651
274740 -0.998583     0.763699   -3.280600    -0.726366       -0.023125
74908   1.001578    -0.796650   -0.979323     0.272030        0.026886
11630  -0.998583    -0.180759   -0.419187     0.052199       -1.449782

        assignments_completed  practice_tests_taken  group_study_hours  \
186295              -1.848621              1.088273           0.190857
127847               1.249846              1.837132          -0.467447
274740               1.249846              1.050003           0.429258
74908                0.927670              0.767184           0.742950
11630                1.249846              2.073317          -0.306943

        notes_quality_score  time_management_score  motivation_level  \
186295            -1.119424              -0.792870          1.504028
127847             0.876631              -0.340624         -0.168394
274740            -0.877387               1.837041         -0.726058
74908              1.621796              -0.878466          0.864803
11630              0.053696               0.147684          1.338676

        mental_health_score  screen_time  social_media_hours  family_income  \
186295             0.915231    -0.226458           -0.665330      -1.169228
127847             1.719739    -0.887421           -1.711826       0.206797
274740             1.928481    -1.069024           -0.112243       0.206797
74908             -1.449969     0.340641            0.549728       1.582822
11630              0.577577    -0.353502            0.506044       1.582822

        parent_education
186295          0.233715
127847         -0.917805
274740          0.233715
74908           0.233715
11630          -0.917805

Preprocessing Complete!
Final X_train shape: (210000, 26)
Final X_test shape: (90000, 26)

In [67]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [68]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(1)
])

In [69]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

In [70]:
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

In [71]:
Dense(128, activation='relu')
Dense(64, activation='relu')

In [72]:
Dense(64, activation='relu')